
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x-labs-bdd"
export APP_NAME="nodey510"



# generated by: jx gitops variables
export APP_NAME="nodey510"
export BRANCH_NAME="master"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x-labs-bdd"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export REPO_NAME="nodey510"
export REPO_OWNER="jstrachan"
