apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: jenkins-x-quickstarts
    repository: node-http
  name: jenkins-x-quickstarts-node-http-fnprs-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineSpec:
    params:
    - default: 0.0.1
      description: the version number for this pipeline which is used as a tag on docker images and helm charts
      name: version
      type: string
    - description: git url to clone
      name: REPO_URL
      type: string
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: revision
      type: string
    - default: source
      description: subdirectory inside of /workspace to clone the git repo
      name: subdirectory
      type: string
    tasks:
    - name: from-build-pack
      params:
      - name: version
        value: $(params.version)
      - name: REPO_URL
        value: $(params.REPO_URL)
      - name: revision
        value: $(params.revision)
      - name: subdirectory
        value: $(params.subdirectory)
      resources: {}
      taskSpec:
        params:
        - default: 0.0.1
          description: the version number for this pipeline which is used as a tag on docker images and helm charts
          name: version
          type: string
        - description: git url to clone
          name: REPO_URL
          type: string
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        - default: source
          description: subdirectory inside of /workspace to clone the git repo
          name: subdirectory
          type: string
        stepTemplate:
          env:
          - name: PIPELINE_KIND
            value: release
          - name: JX_BATCH_MODE
            value: "true"
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - args:
          - -c
          - 'mkdir -p $HOME; git config --global --add user.name $GIT_AUTHOR_NAME; git config --global --add user.email $GIT_AUTHOR_EMAIL; git config --global credential.helper store; git clone $(inputs.params.REPO_URL) $(inputs.params.subdirectory); echo cloned url: $(inputs.params.REPO_URL) to dir: $(inputs.params.subdirectory); cd $(inputs.params.subdirectory); git checkout $(inputs.params.revision); echo checked out revision: $(inputs.params.revision) to dir: $(inputs.params.subdirectory)'
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio/builder-jx:2.1.32-662
          name: git-clone
          resources: {}
          workingDir: /workspace
        - args:
          - gitops
          - git
          - setup
          - --namespace
          - jx-git-operator
          command:
          - jx
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: git-setup
          resources: {}
          workingDir: /workspace
        - args:
          - -c
          - jx step next-version --filename package.json
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: next-version
          resources: {}
        - args:
          - -c
          - jx step tag --version $(cat VERSION)
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: tag-version
          resources: {}
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: setup-builder-home
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - step
          - git
          - merge
          - --verbose
          command:
          - jx
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: git-merge
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-nodejs:2.1.148-767
          name: build-npmrc
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - npm install
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-nodejs:2.1.148-767
          name: build-npm-install
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - CI=true DISPLAY=:99 npm test
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-nodejs:2.1.148-767
          name: build-npm-test
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - source .jx/variables.sh && /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
          command:
          - /busybox/sh
          - -c
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
          - name: NO_GOOGLE_APPLICATION_CREDENTIALS
            value: "true"
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/kaniko-project/executor:debug-v0.24.0
          name: build-container-build
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - jx step changelog --batch-mode --version v${VERSION}
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: promote-changelog
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - jx step helm release
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: promote-helm-release
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - args:
          - jx promote -b --all-auto --timeout 1h
          command:
          - /bin/sh
          - -c
          env:
          - name: VERSION
            value: $(inputs.params.version)
          image: gcr.io/jenkinsxio/jx-cli:3.0.288
          name: promote-jx-promote
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        volumes:
        - emptyDir: {}
          name: workspace-volume
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate:
    ImagePullSecrets: null
    hostNetwork: false
    schedulerName: ""
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
