apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
#  presubmits:
#    - name: ci
#      context: "ci"
#      always_run: true
#      optional: false
#      trigger: "/test"
#      rerun_command: "/retest"
#      source: "pullrequest.yaml"
  postsubmits:
    - name: main
      context: "main"
      source: "release.yaml"
